-- Settings table migration
-- UI Module: Store Settings Management

CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text NOT NULL UNIQUE,
  value text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Updated at trigger
DROP TRIGGER IF EXISTS trg_settings_updated_at ON settings;
CREATE TRIGGER trg_settings_updated_at BEFORE UPDATE ON settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Seed default settings
INSERT INTO settings (key, value) VALUES
  ('store_name', 'শপ নেক্সাস'),
  ('store_email', 'admin@nexuscommerce.io'),
  ('store_currency', 'BDT'),
  ('store_currency_symbol', '৳'),
  ('store_tax_rate', '0.0'),
  ('store_low_stock_threshold', '5'),
  ('store_address', '100 Market Street, San Francisco, CA'),
  ('store_phone', '+1 (415) 555-0142'),
  ('store_timezone', 'America/Los_Angeles'),
  ('store_logo_url', ''),
  ('inventory_alerts_enabled', 'true'),
  ('auto_restock_threshold', '10'),
  ('theme_accent', 'cyan')
ON CONFLICT (key) DO NOTHING;
